// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBepU7lXw1dV0AipEBYtNoV18HDisesJwI',
    appId: '1:821033357635:android:ed292205b887c7b9121ff6',
    messagingSenderId: '821033357635',
    projectId: 'coba1-914b4',
    storageBucket: 'coba1-914b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4GmoCVtRnNy-eODvTJVwsPJOZsFAGitw',
    appId: '1:821033357635:ios:a4503ada3367a06e121ff6',
    messagingSenderId: '821033357635',
    projectId: 'coba1-914b4',
    storageBucket: 'coba1-914b4.firebasestorage.app',
    iosBundleId: 'com.example.cobaFirebase1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAWPNg5GPIEYRQ7d1jBOS_JfHOBbcohD0',
    appId: '1:821033357635:web:d4d83fc507d36048121ff6',
    messagingSenderId: '821033357635',
    projectId: 'coba1-914b4',
    authDomain: 'coba1-914b4.firebaseapp.com',
    storageBucket: 'coba1-914b4.firebasestorage.app',
    measurementId: 'G-WV55FCY2JC',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAWPNg5GPIEYRQ7d1jBOS_JfHOBbcohD0',
    appId: '1:821033357635:web:74eea788d6bdf400121ff6',
    messagingSenderId: '821033357635',
    projectId: 'coba1-914b4',
    authDomain: 'coba1-914b4.firebaseapp.com',
    storageBucket: 'coba1-914b4.firebasestorage.app',
    measurementId: 'G-HZ7C0V34CL',
  );

}